repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        exclude: ^infrastructure/cloudformation-template\.yaml$
    -   id: check-added-large-files
        args: ['--maxkb=16048']
    -   id: check-ast
    -   id: check-json
    -   id: check-toml
    -   id: debug-statements
    -   id: detect-private-key

-   repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
    -   id: isort
        args: ["--profile", "black", "--line-length", "128"]

-   repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
    -   id: autoflake
        args: ["--remove-all-unused-imports", "--remove-unused-variables", "--in-place"]

-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
        args: ["--line-length", "128"]
